### PR TITLE
Add remove pbr from upstream run requirements

### PR DESCRIPTION
**Pull request by xylar**
This merge also adds `pip check` to tests to catch this issue.

`pip check` is giving me trouble in downstream packages because of the lack of `pbr` at runtime.  `pbr` is in the upstream [requrements.txt](https://opendev.org/jjb/python-jenkins/src/branch/master/requirements.txt#L2), but it does not seem to be needed at runtime (it is not referenced anywhere in the package).

Finally, this merge adds me (@xylar) as a maintainer.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
@nicoddemus, if you prefer to maintain this feedstock yourself, no problem, I would be happy to remove myself.  But adding `pbr` to the run environment and adding `pip check` is something that would be really helpful to me for downstream packages.

**Comment by nicoddemus** [comment]
Hi @xylar,

 > @nicoddemus, if you prefer to maintain this feedstock yourself, no problem,

Not at all! I definitely appreciate the help to share maintenance.

> But adding pbr to the run environment and adding pip check is something that would be really helpful to me for downstream packages.

Can you elaborate on that a bit? I ask because `python-jenkins` only requires `pbr` [during build](https://opendev.org/jjb/python-jenkins/src/branch/master/setup.py#L4).

**Comment by xylar** [comment]
@nicoddemus, thanks for the reply!

I don't think it's a build only requirement. It also shows up in https://opendev.org/jjb/python-jenkins/src/branch/master/requirements.txt#L2 That means it gets put into the package's metadata as a runtime requirement and pip check fails if it's not there. If you are quite convinced that it is not both a build and run requirement, we would need a patch to remove it from requirements.txt. And we should probably make an issue upstream as well.

**Comment by xylar** [comment]
@nicoddemus, I looked into this a bit more yesterday and I would tend to agree that `pbr` only makes sense as a `host` requirement.  conda-forge has a mix of packages that depend on `pbr`, with some only requiring `pbr` in `host` and others including it in `run` as well.  I have a feeling that the run requirement isn't necessary for some of these as well, but some to import `pbr` at runtime (e.g. to do version checks).

Anyway, I'm going to switch this PR to add a patch to remove `pbr` from the run requirements.  Hopefully, that's okay with you.

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
@nicoddemus, could you take a look at this when you have a chance?  Thanks!

**Comment by nicoddemus** [comment]
Hi @xylar,

Sorry, only now I could take some time aside to look at this again.

We don't really use `requirements.txt` during the build of the conda package (AFAIU). I think in conda-forge we attempt to change packages only when there's a reason to do it due to a build or runtime failure (and even on those situations it is probably best to also open a PR to fix the issue upstream).

Any reason to explicitly remove `pbr` from `requirements.txt`? Is it causing problems to you downstream?

**Comment by xylar** [comment]
@nicoddemus, sorry, I thought I had explained better but looking back I must be confusing what I posted here with comments I made on another feedstock.  Let me try to give some more background.

First, conda-forge is wanting to run `pip check` as a standard procedure on all feedstocks going forward, see https://github.com/conda-forge/conda-forge.github.io/issues/962.  Thus, `pip check` should be added to the `test` part of the recipe.

If you do this, you will see that it fails because `pbr` is not part of the test environment for this package.  So how does it know that `pbr` should be there?  As far as I can tell, the answer can only be `requirements.txt`, which `pbr` itself parses during package setup.  This metadata becomes part of the metadata for the conda package.  Specifically, if you download the anaconda tarball: 
https://anaconda.org/conda-forge/python-jenkins/1.7.0/download/noarch/python-jenkins-1.7.0-py_0.tar.bz2
it contains a file `site-packages/python_jenkins-1.7.0.dist-info/METADATA` that includes:
```
Requires-Dist: six (>=1.3.0)
Requires-Dist: pbr (>=0.8.2)
Requires-Dist: multi-key-dict
Requires-Dist: requests
```
I don't see anywhere other than `requirements.txt` where this can be coming from.

Because of that metadata, `pip check` will also require `pbr >=0.8.2`.

Downstream packages that have `python-jenkins` as a dependency will also fail when they call `pip check` because the check is recursive (checking all the dependencies' dependencies as well).  So when I try to build a recipe for [apache-airflow-providers-jenkins](https://airflow.apache.org/docs/apache-airflow-providers-jenkins/stable/index.html), which depends on `python-jenkins`, the `pip check` fails.

There are 2 options I can see.  We could trust that the upstream repository has a good reason to have `pbr` as a runtime requirement and we add it here.  If you are not a developer of that repo, that would be my first choice.  Or we could patch `requirements.txt` so `pbr (>=0.8.2)` no longer shows up in `site-packages/python_jenkins-1.7.0.dist-info/METADATA`, as I have done here, and then we wouldn't need it as a runtime dependency.  If you're a developer on https://opendev.org/jjb/python-jenkins and you know for sure that `pbr` isn't needed at runtime, that would be fine as an interim solution, and we would post an issue to hopefully get `pbr` removed from `requirements.txt` before the next release.

**Comment by nicoddemus** [comment]
Thanks a lot for the clear and through explanation!

From my POV, if `pip check` fails due missing `pbr`, I think we can add `pbr` as runtime dependency (which I realize was your first patch, sorry about that).

So we should update the PR:

* Remove the patch
* Add `pbr` as runtime dependency

Would you like me to do it, or want to do it yourself? 

Thanks again, and sorry for the misunderstanding.

**Comment by xylar** [comment]
@nicoddemus, I'm just glad we're on the same page.  It will be very easy for me to switch back to what I had before, so I'll do that.

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
@nicoddemus, okay, once tests pass, I think this should be good to merge.

**Comment by xylar** [comment]
Thanks again for taking the time to understand the issue.

**Review by nicoddemus — APPROVED** [review]
Thanks again @xylar!

**Pull request merged**
